/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.analysis;

import java.util.ArrayList;
import java.util.List;

import minijava.node.AAndExp;
import minijava.node.AArrayAssignStatement;
import minijava.node.AArrayLengthExp;
import minijava.node.AArrayLookupExp;
import minijava.node.AArrayType;
import minijava.node.AAssignStatement;
import minijava.node.ABlockStatement;
import minijava.node.ABooleanType;
import minijava.node.ACallExp;
import minijava.node.AClassDecl;
import minijava.node.AEqualExp;
import minijava.node.AFalseExp;
import minijava.node.AFormal;
import minijava.node.AIdentifierExp;
import minijava.node.AIfStatement;
import minijava.node.AIntType;
import minijava.node.AIntegerLiteralExp;
import minijava.node.ALessThanExp;
import minijava.node.AMainClass;
import minijava.node.AMethodDecl;
import minijava.node.AMinusExp;
import minijava.node.ANewArrayExp;
import minijava.node.ANewObjectExp;
import minijava.node.ANotExp;
import minijava.node.AObjectType;
import minijava.node.APlusExp;
import minijava.node.APrintStatement;
import minijava.node.AProgram;
import minijava.node.AThisExp;
import minijava.node.ATimesExp;
import minijava.node.ATrueExp;
import minijava.node.AVarDecl;
import minijava.node.AWhileStatement;
import minijava.node.Node;
import minijava.node.PClassDecl;
import minijava.node.PExp;
import minijava.node.PFormal;
import minijava.node.PMethodDecl;
import minijava.node.PStatement;
import minijava.node.PVarDecl;
import minijava.node.Start;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPProgram().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAProgram(AProgram node)
    {
        defaultIn(node);
    }

    public void outAProgram(AProgram node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProgram(AProgram node)
    {
        inAProgram(node);
        if(node.getMainClass() != null)
        {
            node.getMainClass().apply(this);
        }
        {
            List<PClassDecl> copy = new ArrayList<PClassDecl>(node.getClasses());
            for(PClassDecl e : copy)
            {
                e.apply(this);
            }
        }
        outAProgram(node);
    }

    public void inAMainClass(AMainClass node)
    {
        defaultIn(node);
    }

    public void outAMainClass(AMainClass node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMainClass(AMainClass node)
    {
        inAMainClass(node);
        if(node.getName() != null)
        {
            node.getName().apply(this);
        }
        if(node.getMainArgs() != null)
        {
            node.getMainArgs().apply(this);
        }
        if(node.getStatement() != null)
        {
            node.getStatement().apply(this);
        }
        outAMainClass(node);
    }

    public void inAClassDecl(AClassDecl node)
    {
        defaultIn(node);
    }

    public void outAClassDecl(AClassDecl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAClassDecl(AClassDecl node)
    {
        inAClassDecl(node);
        if(node.getName() != null)
        {
            node.getName().apply(this);
        }
        if(node.getSuper() != null)
        {
            node.getSuper().apply(this);
        }
        {
            List<PVarDecl> copy = new ArrayList<PVarDecl>(node.getAttributes());
            for(PVarDecl e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PMethodDecl> copy = new ArrayList<PMethodDecl>(node.getMethods());
            for(PMethodDecl e : copy)
            {
                e.apply(this);
            }
        }
        outAClassDecl(node);
    }

    public void inAVarDecl(AVarDecl node)
    {
        defaultIn(node);
    }

    public void outAVarDecl(AVarDecl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarDecl(AVarDecl node)
    {
        inAVarDecl(node);
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        if(node.getName() != null)
        {
            node.getName().apply(this);
        }
        outAVarDecl(node);
    }

    public void inAMethodDecl(AMethodDecl node)
    {
        defaultIn(node);
    }

    public void outAMethodDecl(AMethodDecl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMethodDecl(AMethodDecl node)
    {
        inAMethodDecl(node);
        if(node.getReturnType() != null)
        {
            node.getReturnType().apply(this);
        }
        if(node.getName() != null)
        {
            node.getName().apply(this);
        }
        {
            List<PFormal> copy = new ArrayList<PFormal>(node.getFormals());
            for(PFormal e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PVarDecl> copy = new ArrayList<PVarDecl>(node.getLocals());
            for(PVarDecl e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PStatement> copy = new ArrayList<PStatement>(node.getBody());
            for(PStatement e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getReturnExp() != null)
        {
            node.getReturnExp().apply(this);
        }
        outAMethodDecl(node);
    }

    public void inAFormal(AFormal node)
    {
        defaultIn(node);
    }

    public void outAFormal(AFormal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFormal(AFormal node)
    {
        inAFormal(node);
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        if(node.getName() != null)
        {
            node.getName().apply(this);
        }
        outAFormal(node);
    }

    public void inAArrayType(AArrayType node)
    {
        defaultIn(node);
    }

    public void outAArrayType(AArrayType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArrayType(AArrayType node)
    {
        inAArrayType(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        outAArrayType(node);
    }

    public void inABooleanType(ABooleanType node)
    {
        defaultIn(node);
    }

    public void outABooleanType(ABooleanType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABooleanType(ABooleanType node)
    {
        inABooleanType(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        outABooleanType(node);
    }

    public void inAIntType(AIntType node)
    {
        defaultIn(node);
    }

    public void outAIntType(AIntType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntType(AIntType node)
    {
        inAIntType(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        outAIntType(node);
    }

    public void inAObjectType(AObjectType node)
    {
        defaultIn(node);
    }

    public void outAObjectType(AObjectType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAObjectType(AObjectType node)
    {
        inAObjectType(node);
        if(node.getName() != null)
        {
            node.getName().apply(this);
        }
        outAObjectType(node);
    }

    public void inABlockStatement(ABlockStatement node)
    {
        defaultIn(node);
    }

    public void outABlockStatement(ABlockStatement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlockStatement(ABlockStatement node)
    {
        inABlockStatement(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        {
            List<PStatement> copy = new ArrayList<PStatement>(node.getStatements());
            for(PStatement e : copy)
            {
                e.apply(this);
            }
        }
        outABlockStatement(node);
    }

    public void inAIfStatement(AIfStatement node)
    {
        defaultIn(node);
    }

    public void outAIfStatement(AIfStatement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfStatement(AIfStatement node)
    {
        inAIfStatement(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        if(node.getThenClause() != null)
        {
            node.getThenClause().apply(this);
        }
        if(node.getElseClause() != null)
        {
            node.getElseClause().apply(this);
        }
        outAIfStatement(node);
    }

    public void inAWhileStatement(AWhileStatement node)
    {
        defaultIn(node);
    }

    public void outAWhileStatement(AWhileStatement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAWhileStatement(AWhileStatement node)
    {
        inAWhileStatement(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        outAWhileStatement(node);
    }

    public void inAPrintStatement(APrintStatement node)
    {
        defaultIn(node);
    }

    public void outAPrintStatement(APrintStatement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrintStatement(APrintStatement node)
    {
        inAPrintStatement(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        outAPrintStatement(node);
    }

    public void inAAssignStatement(AAssignStatement node)
    {
        defaultIn(node);
    }

    public void outAAssignStatement(AAssignStatement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAssignStatement(AAssignStatement node)
    {
        inAAssignStatement(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        if(node.getTarget() != null)
        {
            node.getTarget().apply(this);
        }
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        outAAssignStatement(node);
    }

    public void inAArrayAssignStatement(AArrayAssignStatement node)
    {
        defaultIn(node);
    }

    public void outAArrayAssignStatement(AArrayAssignStatement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArrayAssignStatement(AArrayAssignStatement node)
    {
        inAArrayAssignStatement(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        if(node.getTarget() != null)
        {
            node.getTarget().apply(this);
        }
        if(node.getIndex() != null)
        {
            node.getIndex().apply(this);
        }
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        outAArrayAssignStatement(node);
    }

    public void inAAndExp(AAndExp node)
    {
        defaultIn(node);
    }

    public void outAAndExp(AAndExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAndExp(AAndExp node)
    {
        inAAndExp(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        if(node.getLhs() != null)
        {
            node.getLhs().apply(this);
        }
        if(node.getRhs() != null)
        {
            node.getRhs().apply(this);
        }
        outAAndExp(node);
    }

    public void inAEqualExp(AEqualExp node)
    {
        defaultIn(node);
    }

    public void outAEqualExp(AEqualExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEqualExp(AEqualExp node)
    {
        inAEqualExp(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        if(node.getLhs() != null)
        {
            node.getLhs().apply(this);
        }
        if(node.getRhs() != null)
        {
            node.getRhs().apply(this);
        }
        outAEqualExp(node);
    }

    public void inALessThanExp(ALessThanExp node)
    {
        defaultIn(node);
    }

    public void outALessThanExp(ALessThanExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALessThanExp(ALessThanExp node)
    {
        inALessThanExp(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        if(node.getLhs() != null)
        {
            node.getLhs().apply(this);
        }
        if(node.getRhs() != null)
        {
            node.getRhs().apply(this);
        }
        outALessThanExp(node);
    }

    public void inATimesExp(ATimesExp node)
    {
        defaultIn(node);
    }

    public void outATimesExp(ATimesExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATimesExp(ATimesExp node)
    {
        inATimesExp(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        if(node.getLhs() != null)
        {
            node.getLhs().apply(this);
        }
        if(node.getRhs() != null)
        {
            node.getRhs().apply(this);
        }
        outATimesExp(node);
    }

    public void inAPlusExp(APlusExp node)
    {
        defaultIn(node);
    }

    public void outAPlusExp(APlusExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPlusExp(APlusExp node)
    {
        inAPlusExp(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        if(node.getLhs() != null)
        {
            node.getLhs().apply(this);
        }
        if(node.getRhs() != null)
        {
            node.getRhs().apply(this);
        }
        outAPlusExp(node);
    }

    public void inAMinusExp(AMinusExp node)
    {
        defaultIn(node);
    }

    public void outAMinusExp(AMinusExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMinusExp(AMinusExp node)
    {
        inAMinusExp(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        if(node.getLhs() != null)
        {
            node.getLhs().apply(this);
        }
        if(node.getRhs() != null)
        {
            node.getRhs().apply(this);
        }
        outAMinusExp(node);
    }

    public void inAArrayLookupExp(AArrayLookupExp node)
    {
        defaultIn(node);
    }

    public void outAArrayLookupExp(AArrayLookupExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArrayLookupExp(AArrayLookupExp node)
    {
        inAArrayLookupExp(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        if(node.getArray() != null)
        {
            node.getArray().apply(this);
        }
        if(node.getIndex() != null)
        {
            node.getIndex().apply(this);
        }
        outAArrayLookupExp(node);
    }

    public void inAArrayLengthExp(AArrayLengthExp node)
    {
        defaultIn(node);
    }

    public void outAArrayLengthExp(AArrayLengthExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArrayLengthExp(AArrayLengthExp node)
    {
        inAArrayLengthExp(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        if(node.getArray() != null)
        {
            node.getArray().apply(this);
        }
        outAArrayLengthExp(node);
    }

    public void inACallExp(ACallExp node)
    {
        defaultIn(node);
    }

    public void outACallExp(ACallExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACallExp(ACallExp node)
    {
        inACallExp(node);
        if(node.getObject() != null)
        {
            node.getObject().apply(this);
        }
        if(node.getMethod() != null)
        {
            node.getMethod().apply(this);
        }
        {
            List<PExp> copy = new ArrayList<PExp>(node.getActuals());
            for(PExp e : copy)
            {
                e.apply(this);
            }
        }
        outACallExp(node);
    }

    public void inAIntegerLiteralExp(AIntegerLiteralExp node)
    {
        defaultIn(node);
    }

    public void outAIntegerLiteralExp(AIntegerLiteralExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntegerLiteralExp(AIntegerLiteralExp node)
    {
        inAIntegerLiteralExp(node);
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        outAIntegerLiteralExp(node);
    }

    public void inATrueExp(ATrueExp node)
    {
        defaultIn(node);
    }

    public void outATrueExp(ATrueExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATrueExp(ATrueExp node)
    {
        inATrueExp(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        outATrueExp(node);
    }

    public void inAFalseExp(AFalseExp node)
    {
        defaultIn(node);
    }

    public void outAFalseExp(AFalseExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFalseExp(AFalseExp node)
    {
        inAFalseExp(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        outAFalseExp(node);
    }

    public void inAIdentifierExp(AIdentifierExp node)
    {
        defaultIn(node);
    }

    public void outAIdentifierExp(AIdentifierExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdentifierExp(AIdentifierExp node)
    {
        inAIdentifierExp(node);
        if(node.getName() != null)
        {
            node.getName().apply(this);
        }
        outAIdentifierExp(node);
    }

    public void inAThisExp(AThisExp node)
    {
        defaultIn(node);
    }

    public void outAThisExp(AThisExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAThisExp(AThisExp node)
    {
        inAThisExp(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        outAThisExp(node);
    }

    public void inANewArrayExp(ANewArrayExp node)
    {
        defaultIn(node);
    }

    public void outANewArrayExp(ANewArrayExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANewArrayExp(ANewArrayExp node)
    {
        inANewArrayExp(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        if(node.getSize() != null)
        {
            node.getSize().apply(this);
        }
        outANewArrayExp(node);
    }

    public void inANewObjectExp(ANewObjectExp node)
    {
        defaultIn(node);
    }

    public void outANewObjectExp(ANewObjectExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANewObjectExp(ANewObjectExp node)
    {
        inANewObjectExp(node);
        if(node.getName() != null)
        {
            node.getName().apply(this);
        }
        outANewObjectExp(node);
    }

    public void inANotExp(ANotExp node)
    {
        defaultIn(node);
    }

    public void outANotExp(ANotExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANotExp(ANotExp node)
    {
        inANotExp(node);
        if(node.getToken() != null)
        {
            node.getToken().apply(this);
        }
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        outANotExp(node);
    }
}
