/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class AAndExp extends PExp
{
    private final LinkedList<PExp> _andexps_ = new LinkedList<PExp>();

    public AAndExp()
    {
        // Constructor
    }

    public AAndExp(
        @SuppressWarnings("hiding") List<PExp> _andexps_)
    {
        // Constructor
        setAndexps(_andexps_);

    }

    @Override
    public Object clone()
    {
        return new AAndExp(
            cloneList(this._andexps_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndExp(this);
    }

    public LinkedList<PExp> getAndexps()
    {
        return this._andexps_;
    }

    public void setAndexps(List<PExp> list)
    {
        this._andexps_.clear();
        this._andexps_.addAll(list);
        for(PExp e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._andexps_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._andexps_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PExp> i = this._andexps_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
