/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class ACallExp extends PExp
{
    private PExp _object_;
    private TId _methodName_;
    private final LinkedList<PExp> _args_ = new LinkedList<PExp>();

    public ACallExp()
    {
        // Constructor
    }

    public ACallExp(
        @SuppressWarnings("hiding") PExp _object_,
        @SuppressWarnings("hiding") TId _methodName_,
        @SuppressWarnings("hiding") List<PExp> _args_)
    {
        // Constructor
        setObject(_object_);

        setMethodName(_methodName_);

        setArgs(_args_);

    }

    @Override
    public Object clone()
    {
        return new ACallExp(
            cloneNode(this._object_),
            cloneNode(this._methodName_),
            cloneList(this._args_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACallExp(this);
    }

    public PExp getObject()
    {
        return this._object_;
    }

    public void setObject(PExp node)
    {
        if(this._object_ != null)
        {
            this._object_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._object_ = node;
    }

    public TId getMethodName()
    {
        return this._methodName_;
    }

    public void setMethodName(TId node)
    {
        if(this._methodName_ != null)
        {
            this._methodName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._methodName_ = node;
    }

    public LinkedList<PExp> getArgs()
    {
        return this._args_;
    }

    public void setArgs(List<PExp> list)
    {
        this._args_.clear();
        this._args_.addAll(list);
        for(PExp e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._object_)
            + toString(this._methodName_)
            + toString(this._args_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._object_ == child)
        {
            this._object_ = null;
            return;
        }

        if(this._methodName_ == child)
        {
            this._methodName_ = null;
            return;
        }

        if(this._args_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._object_ == oldChild)
        {
            setObject((PExp) newChild);
            return;
        }

        if(this._methodName_ == oldChild)
        {
            setMethodName((TId) newChild);
            return;
        }

        for(ListIterator<PExp> i = this._args_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
