/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class AIdlistExp extends PExp
{
    private TId _id_;
    private final LinkedList<PExp> _explist_ = new LinkedList<PExp>();

    public AIdlistExp()
    {
        // Constructor
    }

    public AIdlistExp(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") List<PExp> _explist_)
    {
        // Constructor
        setId(_id_);

        setExplist(_explist_);

    }

    @Override
    public Object clone()
    {
        return new AIdlistExp(
            cloneNode(this._id_),
            cloneList(this._explist_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdlistExp(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public LinkedList<PExp> getExplist()
    {
        return this._explist_;
    }

    public void setExplist(List<PExp> list)
    {
        this._explist_.clear();
        this._explist_.addAll(list);
        for(PExp e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._explist_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._explist_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator<PExp> i = this._explist_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
