/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class ALessExp extends PExp
{
    private final LinkedList<PExp> _lessexps_ = new LinkedList<PExp>();

    public ALessExp()
    {
        // Constructor
    }

    public ALessExp(
        @SuppressWarnings("hiding") List<PExp> _lessexps_)
    {
        // Constructor
        setLessexps(_lessexps_);

    }

    @Override
    public Object clone()
    {
        return new ALessExp(
            cloneList(this._lessexps_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALessExp(this);
    }

    public LinkedList<PExp> getLessexps()
    {
        return this._lessexps_;
    }

    public void setLessexps(List<PExp> list)
    {
        this._lessexps_.clear();
        this._lessexps_.addAll(list);
        for(PExp e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lessexps_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lessexps_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PExp> i = this._lessexps_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
