/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AVardecl extends PVardecl
{
    private PType _type_;
    private TId _varname_;

    public AVardecl()
    {
        // Constructor
    }

    public AVardecl(
        @SuppressWarnings("hiding") PType _type_,
        @SuppressWarnings("hiding") TId _varname_)
    {
        // Constructor
        setType(_type_);

        setVarname(_varname_);

    }

    @Override
    public Object clone()
    {
        return new AVardecl(
            cloneNode(this._type_),
            cloneNode(this._varname_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVardecl(this);
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public TId getVarname()
    {
        return this._varname_;
    }

    public void setVarname(TId node)
    {
        if(this._varname_ != null)
        {
            this._varname_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varname_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._type_)
            + toString(this._varname_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._varname_ == child)
        {
            this._varname_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(this._varname_ == oldChild)
        {
            setVarname((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
