/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.Analysis;

@SuppressWarnings("nls")
public final class AArrayLengthExp extends PExp
{
    private TLength _token_;
    private PExp _array_;

    public AArrayLengthExp()
    {
        // Constructor
    }

    public AArrayLengthExp(
        @SuppressWarnings("hiding") TLength _token_,
        @SuppressWarnings("hiding") PExp _array_)
    {
        // Constructor
        setToken(_token_);

        setArray(_array_);

    }

    @Override
    public Object clone()
    {
        return new AArrayLengthExp(
            cloneNode(this._token_),
            cloneNode(this._array_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayLengthExp(this);
    }

    public TLength getToken()
    {
        return this._token_;
    }

    public void setToken(TLength node)
    {
        if(this._token_ != null)
        {
            this._token_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._token_ = node;
    }

    public PExp getArray()
    {
        return this._array_;
    }

    public void setArray(PExp node)
    {
        if(this._array_ != null)
        {
            this._array_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._array_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._token_)
            + toString(this._array_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._token_ == child)
        {
            this._token_ = null;
            return;
        }

        if(this._array_ == child)
        {
            this._array_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._token_ == oldChild)
        {
            setToken((TLength) newChild);
            return;
        }

        if(this._array_ == oldChild)
        {
            setArray((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
