/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class AArrayAssignStatement extends PStatement
{
    private TId _id_;
    private PExp _arrayindex_;
    private PExp _value_;

    public AArrayAssignStatement()
    {
        // Constructor
    }

    public AArrayAssignStatement(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PExp _arrayindex_,
        @SuppressWarnings("hiding") PExp _value_)
    {
        // Constructor
        setId(_id_);

        setArrayindex(_arrayindex_);

        setValue(_value_);

    }

    @Override
    public Object clone()
    {
        return new AArrayAssignStatement(
            cloneNode(this._id_),
            cloneNode(this._arrayindex_),
            cloneNode(this._value_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayAssignStatement(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PExp getArrayindex()
    {
        return this._arrayindex_;
    }

    public void setArrayindex(PExp node)
    {
        if(this._arrayindex_ != null)
        {
            this._arrayindex_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrayindex_ = node;
    }

    public PExp getValue()
    {
        return this._value_;
    }

    public void setValue(PExp node)
    {
        if(this._value_ != null)
        {
            this._value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._value_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._arrayindex_)
            + toString(this._value_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._arrayindex_ == child)
        {
            this._arrayindex_ = null;
            return;
        }

        if(this._value_ == child)
        {
            this._value_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._arrayindex_ == oldChild)
        {
            setArrayindex((PExp) newChild);
            return;
        }

        if(this._value_ == oldChild)
        {
            setValue((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
