/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import java.util.*;
import minijava.analysis.*;

@SuppressWarnings("nls")
public final class ACallExp extends PExp
{
    private PExp _object_;
    private TId _method_;
    private final LinkedList<PExp> _actuals_ = new LinkedList<PExp>();

    public ACallExp()
    {
        // Constructor
    }

    public ACallExp(
        @SuppressWarnings("hiding") PExp _object_,
        @SuppressWarnings("hiding") TId _method_,
        @SuppressWarnings("hiding") List<PExp> _actuals_)
    {
        // Constructor
        setObject(_object_);

        setMethod(_method_);

        setActuals(_actuals_);

    }

    @Override
    public Object clone()
    {
        return new ACallExp(
            cloneNode(this._object_),
            cloneNode(this._method_),
            cloneList(this._actuals_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACallExp(this);
    }

    public PExp getObject()
    {
        return this._object_;
    }

    public void setObject(PExp node)
    {
        if(this._object_ != null)
        {
            this._object_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._object_ = node;
    }

    public TId getMethod()
    {
        return this._method_;
    }

    public void setMethod(TId node)
    {
        if(this._method_ != null)
        {
            this._method_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._method_ = node;
    }

    public LinkedList<PExp> getActuals()
    {
        return this._actuals_;
    }

    public void setActuals(List<PExp> list)
    {
        this._actuals_.clear();
        this._actuals_.addAll(list);
        for(PExp e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._object_)
            + toString(this._method_)
            + toString(this._actuals_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._object_ == child)
        {
            this._object_ = null;
            return;
        }

        if(this._method_ == child)
        {
            this._method_ = null;
            return;
        }

        if(this._actuals_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._object_ == oldChild)
        {
            setObject((PExp) newChild);
            return;
        }

        if(this._method_ == oldChild)
        {
            setMethod((TId) newChild);
            return;
        }

        for(ListIterator<PExp> i = this._actuals_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
